Hw30.1
joej0e/ILibrary pull request #1
Opened 2019-10-17 16:49 UTC by joej0e

2019-10-17 17:38 UTC, boroda4436 commented
@joej0e новий пул реквест?) А що трапилося зі старим?

2019-10-18 06:51 UTC, joej0e commented
> @joej0e новий пул реквест?) А що трапилося зі старим?

Видалила проект з ідеї, тому що після оновлення ідеї, коли мій проект відкрився, залежності перестали підтягуватися. Invalidate cahes і reimport не допомгло

2019-10-18 10:52 UTC, boroda4436 approved these changes

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/config/AppConfig.java
> +        factoryBean.setAnnotatedClasses(User.class, Book.class, Rent.class, Author.class);
we can use this line here:
factoryBean.setPackagesToScan("spring.entity");

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/config/AppConfig.java
> +
remove one redundant line at the end  of the file

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/dao/AuthorDao.java
> +
the same

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/dao/LibraryDao.java
> +
remove two lines

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/dao/impl/AuthorDaoImpl.java
> +        @SuppressWarnings("unchecked")
try removing this line in all query
Bohdan wrote how to do it in slack

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/dao/impl/LibraryDaoImpl.java
> +        Query queryGetBooks = sessionFactory.createEntityManager().createNativeQuery("select library.books.book_id," +
too long line

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/dao/impl/LibraryDaoImpl.java
> +            System.out.println("Book isn't available!");
better remove sout

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/dao/impl/LibraryDaoImpl.java
> +        Query queryGetBooks = sessionFactory.createEntityManager().createNativeQuery("select library.books.book_id," +
too ling line
try using `like` in all query where we find books and authors by name, surname and title

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/dao/impl/LibraryDaoImpl.java
> +        Query queryGetBooks = sessionFactory.createEntityManager().createNativeQuery("select library.books.book_id," +
the same

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/entity/Book.java
> +    private List<User> users = new ArrayList<>();
book can't know anything about user

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/entity/Rent.java
> +    Long userId;
add access modifier
try to use `onetoone`here

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/entity/Rent.java
> +    Long book_id;
the same

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/service/AuthorService.java
> +    List<Author> listAuthors();
add empty line between methods

2019-10-21 03:38 UTC, Sofasmile commented on src/main/java/spring/service/LibraryService.java
> +
redundant lines at the end of the file

2019-10-22 09:19 UTC, boroda4436 requested changes

2019-10-22 09:19 UTC, boroda4436 commented on src/main/java/spring/MainApp.java
> +        Book catcher_in_the_rye = bookService.add(new Book(
@joej0e Сконфігуруй, будь-ласка, travis для цього репозиторію. Якщо виникнуть питання - можеш задати їх Юрі або Саші Буніну. Вони вже робили це

2019-10-22 09:19 UTC, boroda4436 commented on src/main/java/spring/config/WebConfig.java
> +
@joej0e Занадто багато пустих рядків в кінці файлу. Достатньо одного

2019-10-22 09:19 UTC, boroda4436 commented on src/main/java/spring/controller/BookController.java
> +import java.util.List;
@joej0e mvn clean package? Ти робиш цю перевірку перед тим як пушити коміт?

2019-10-22 09:19 UTC, boroda4436 commented on src/main/java/spring/controller/BookController.java
> +    public String bookInfo(@RequestParam("book_title") String title, Model model) {
@joej0e перероби будь-ласка на @ PathVariable

2019-10-22 09:19 UTC, boroda4436 commented on src/main/java/spring/dao/BookDao.java
> +
зайвий рядок

2019-10-22 09:19 UTC, boroda4436 commented on src/main/java/spring/dao/UserDao.java
> +import java.util.List;
@joej0e налаштуй автоматичний імпорт щоб java.util. був над spring.

2019-10-22 09:19 UTC, boroda4436 commented on src/main/java/spring/dao/impl/LibraryDaoImpl.java
> +        Query queryGetBooks = sessionFactory.createEntityManager()
@joej0e Можемо спростити цей запит?

2019-10-22 09:19 UTC, boroda4436 commented on src/main/java/spring/entity/Rent.java
> +
mvn clean package

2019-11-15 16:39 UTC, merged